name: Sync Branches with Main

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Faz o checkout completo, incluindo referências de outras branches remotas

      - name: Delete dev branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="dev"
          # Atualiza as referências remotas para garantir que a branch dev seja identificada
          git fetch origin
          if git ls-remote --exit-code --heads origin $BRANCH_NAME; then
            echo "Deleting branch $BRANCH_NAME..."
            git push origin --delete $BRANCH_NAME
          else
            echo "Branch $BRANCH_NAME does not exist on remote, skipping deletion."
          fi