name: Delete Dev Branch After Merge

on:
  push:
    branches:
      - main

jobs:
  delete_dev_branch:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Delete dev branch
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Usando o PAT
        run: |
          BRANCH_NAME="dev"
          git fetch origin
          if git ls-remote --exit-code --heads origin $BRANCH_NAME; then
            echo "Deleting branch $BRANCH_NAME..."
            git push https://$PERSONAL_ACCESS_TOKEN@github.com/adintelti/TopDown2DUnityGame.git --delete $BRANCH_NAME
          else
            echo "Branch $BRANCH_NAME does not exist on remote, skipping deletion."
          fi