name: Sync Branches with Main

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete dev branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="dev"
          if git show-ref --verify --quiet refs/heads/$BRANCH_NAME; then
            echo "Deleting branch $BRANCH_NAME..."
            git push origin --delete $BRANCH_NAME
          else
            echo "Branch $BRANCH_NAME does not exist, skipping deletion."
          fi