name: Sync Branches with Main

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update branch dev with main
        run: |
          git fetch origin
          git checkout dev
          git merge origin/main
          git push origin dev
